(let (head tail name)
  (setf head 0)
  (setf tail 0)
  (format t "Who are you?~%>")
  (setf name (read))
  (format t "Hello, ~:(~A~)~%" name)
  (format t "Tossing a coin...~%")
  (dotimes (x 3) (progn (if (evenp (random 2))
                            (progn (incf head)
                                   (format t "Round ~A: Head~%" x))
                            (progn (incf tail)
                                   (format t "Round ~A: Tail~%" x))
                            )))
  (format t "Heads: ~A, Tails: ~A~%" head tail)
  (if (> head tail)
      (progn (format t "You won~%"))
      (progn (format t "You lost~%"))
      )
)
